version: '3.7'

services:
  build_app:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes:
      - app:/opt/app

  webapp:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - app:/opt/apache-tomcat-10.0.23/webapps
volumes:
  app: